# Generated by Django 3.2.3 on 2021-05-26 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZillowEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zillow_id', models.PositiveIntegerField(null=True)),
                ('rentzestimate_amount', models.PositiveIntegerField(null=True)),
                ('rentzestimate_last_updated', models.DateField(null=True)),
                ('zestimate_amount', models.PositiveIntegerField(null=True)),
                ('zestimate_last_updated', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_unit', models.CharField(default='SqFt', max_length=10)),
                ('bathrooms', models.FloatField(null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(null=True)),
                ('home_size', models.PositiveIntegerField(null=True)),
                ('home_type', models.CharField(choices=[('SingleFamily', 'Single Family'), ('Condominium', 'Condominium'), ('MultiFamily2to4', 'Multi-Family (2 to 4)'), ('VacantResidentialLand', 'Vacant Residential Land'), ('Apartment', 'Apartment')], default='SingleFamily', max_length=22)),
                ('last_sold_date', models.DateField(null=True)),
                ('last_sold_price', models.PositiveIntegerField(null=True)),
                ('link', models.URLField(null=True)),
                ('price', models.CharField(default='', max_length=7)),
                ('property_size', models.PositiveIntegerField(null=True)),
                ('rent_price', models.PositiveIntegerField(null=True)),
                ('tax_value', models.FloatField(null=True)),
                ('tax_year', models.CharField(default='', max_length=4)),
                ('year_built', models.CharField(default='', max_length=4)),
                ('address', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=5)),
                ('zillow_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='api.zillowestimate')),
            ],
        ),
    ]
